//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Trello.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuantityBoard {
            get {
                return ((int)(this["QuantityBoard"]));
            }
            set {
                this["QuantityBoard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BoardName1 {
            get {
                return ((string)(this["BoardName1"]));
            }
            set {
                this["BoardName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BoardName2 {
            get {
                return ((string)(this["BoardName2"]));
            }
            set {
                this["BoardName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BoardName3 {
            get {
                return ((string)(this["BoardName3"]));
            }
            set {
                this["BoardName3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackgroundNumber1 {
            get {
                return ((int)(this["BackgroundNumber1"]));
            }
            set {
                this["BackgroundNumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackgroundNumber2 {
            get {
                return ((int)(this["BackgroundNumber2"]));
            }
            set {
                this["BackgroundNumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackgroundNumber3 {
            get {
                return ((int)(this["BackgroundNumber3"]));
            }
            set {
                this["BackgroundNumber3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board1ListQuantity {
            get {
                return ((int)(this["Board1ListQuantity"]));
            }
            set {
                this["Board1ListQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board2ListQuantity {
            get {
                return ((int)(this["Board2ListQuantity"]));
            }
            set {
                this["Board2ListQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board3ListQuantity {
            get {
                return ((int)(this["Board3ListQuantity"]));
            }
            set {
                this["Board3ListQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Board1Favorites {
            get {
                return ((bool)(this["Board1Favorites"]));
            }
            set {
                this["Board1Favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Board2Favorites {
            get {
                return ((bool)(this["Board2Favorites"]));
            }
            set {
                this["Board2Favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Board3Favorites {
            get {
                return ((bool)(this["Board3Favorites"]));
            }
            set {
                this["Board3Favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List1Name {
            get {
                return ((string)(this["Board1List1Name"]));
            }
            set {
                this["Board1List1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List2Name {
            get {
                return ((string)(this["Board1List2Name"]));
            }
            set {
                this["Board1List2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List3Name {
            get {
                return ((string)(this["Board1List3Name"]));
            }
            set {
                this["Board1List3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List1Name {
            get {
                return ((string)(this["Board2List1Name"]));
            }
            set {
                this["Board2List1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List2Name {
            get {
                return ((string)(this["Board2List2Name"]));
            }
            set {
                this["Board2List2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List3Name {
            get {
                return ((string)(this["Board2List3Name"]));
            }
            set {
                this["Board2List3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List1Name {
            get {
                return ((string)(this["Board3List1Name"]));
            }
            set {
                this["Board3List1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List2Name {
            get {
                return ((string)(this["Board3List2Name"]));
            }
            set {
                this["Board3List2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List3Name {
            get {
                return ((string)(this["Board3List3Name"]));
            }
            set {
                this["Board3List3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board1List1CardQuantity {
            get {
                return ((int)(this["Board1List1CardQuantity"]));
            }
            set {
                this["Board1List1CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board1List2CardQuantity {
            get {
                return ((int)(this["Board1List2CardQuantity"]));
            }
            set {
                this["Board1List2CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board1List3CardQuantity {
            get {
                return ((int)(this["Board1List3CardQuantity"]));
            }
            set {
                this["Board1List3CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board2List1CardQuantity {
            get {
                return ((int)(this["Board2List1CardQuantity"]));
            }
            set {
                this["Board2List1CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board2List2CardQuantity {
            get {
                return ((int)(this["Board2List2CardQuantity"]));
            }
            set {
                this["Board2List2CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board2List3CardQuantity {
            get {
                return ((int)(this["Board2List3CardQuantity"]));
            }
            set {
                this["Board2List3CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board3List1CardQuantity {
            get {
                return ((int)(this["Board3List1CardQuantity"]));
            }
            set {
                this["Board3List1CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board3List2CardQuantity {
            get {
                return ((int)(this["Board3List2CardQuantity"]));
            }
            set {
                this["Board3List2CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Board3List3CardQuantity {
            get {
                return ((int)(this["Board3List3CardQuantity"]));
            }
            set {
                this["Board3List3CardQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List1Card1Text {
            get {
                return ((string)(this["Board1List1Card1Text"]));
            }
            set {
                this["Board1List1Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List1Card2Text {
            get {
                return ((string)(this["Board1List1Card2Text"]));
            }
            set {
                this["Board1List1Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List1Card3Text {
            get {
                return ((string)(this["Board1List1Card3Text"]));
            }
            set {
                this["Board1List1Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List2Card1Text {
            get {
                return ((string)(this["Board1List2Card1Text"]));
            }
            set {
                this["Board1List2Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List2Card2Text {
            get {
                return ((string)(this["Board1List2Card2Text"]));
            }
            set {
                this["Board1List2Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List2Card3Text {
            get {
                return ((string)(this["Board1List2Card3Text"]));
            }
            set {
                this["Board1List2Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List3Card1Text {
            get {
                return ((string)(this["Board1List3Card1Text"]));
            }
            set {
                this["Board1List3Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List3Card2Text {
            get {
                return ((string)(this["Board1List3Card2Text"]));
            }
            set {
                this["Board1List3Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board1List3Card3Text {
            get {
                return ((string)(this["Board1List3Card3Text"]));
            }
            set {
                this["Board1List3Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List1Card1Text {
            get {
                return ((string)(this["Board2List1Card1Text"]));
            }
            set {
                this["Board2List1Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List1Card2Text {
            get {
                return ((string)(this["Board2List1Card2Text"]));
            }
            set {
                this["Board2List1Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List1Card3Text {
            get {
                return ((string)(this["Board2List1Card3Text"]));
            }
            set {
                this["Board2List1Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List2Card1Text {
            get {
                return ((string)(this["Board2List2Card1Text"]));
            }
            set {
                this["Board2List2Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List2Card2Text {
            get {
                return ((string)(this["Board2List2Card2Text"]));
            }
            set {
                this["Board2List2Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List2Card3Text {
            get {
                return ((string)(this["Board2List2Card3Text"]));
            }
            set {
                this["Board2List2Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List3Card1Text {
            get {
                return ((string)(this["Board2List3Card1Text"]));
            }
            set {
                this["Board2List3Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List3Card2Text {
            get {
                return ((string)(this["Board2List3Card2Text"]));
            }
            set {
                this["Board2List3Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board2List3Card3Text {
            get {
                return ((string)(this["Board2List3Card3Text"]));
            }
            set {
                this["Board2List3Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List1Card1Text {
            get {
                return ((string)(this["Board3List1Card1Text"]));
            }
            set {
                this["Board3List1Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List1Card2Text {
            get {
                return ((string)(this["Board3List1Card2Text"]));
            }
            set {
                this["Board3List1Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List1Card3Text {
            get {
                return ((string)(this["Board3List1Card3Text"]));
            }
            set {
                this["Board3List1Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List2Card1Text {
            get {
                return ((string)(this["Board3List2Card1Text"]));
            }
            set {
                this["Board3List2Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List2Card2Text {
            get {
                return ((string)(this["Board3List2Card2Text"]));
            }
            set {
                this["Board3List2Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List2Card3Text {
            get {
                return ((string)(this["Board3List2Card3Text"]));
            }
            set {
                this["Board3List2Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List3Card1Text {
            get {
                return ((string)(this["Board3List3Card1Text"]));
            }
            set {
                this["Board3List3Card1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List3Card2Text {
            get {
                return ((string)(this["Board3List3Card2Text"]));
            }
            set {
                this["Board3List3Card2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Board3List3Card3Text {
            get {
                return ((string)(this["Board3List3Card3Text"]));
            }
            set {
                this["Board3List3Card3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentUploadNumberBoard {
            get {
                return ((int)(this["CurrentUploadNumberBoard"]));
            }
            set {
                this["CurrentUploadNumberBoard"] = value;
            }
        }
    }
}
